language: rust
sudo: false
dist: trusty
rust:
- 1.27.0
- stable
- beta
- nightly

# Install travis-cargo which sets `--feature unstable` for nightly builds automatically
before_script:
  - |
      pip install 'travis-cargo<0.2' --user &&
      export PATH=$HOME/.local/bin:$PATH

script:
  - |
      travis-cargo build -- --all &&
      travis-cargo test -- -p proptest &&
      travis-cargo --only stable build -- -p proptest --no-default-features --features fork &&
      travis-cargo --only stable build -- -p proptest --lib --no-default-features --features std &&
      travis-cargo --only nightly build -- -p proptest --no-default-features --features "alloc nightly unstable" &&
      (cd proptest/test-persistence-location && ./run-tests.sh) &&
      travis-cargo --only nightly test -- -p proptest-derive

cache: cargo
