language: rust
sudo: false
dist: trusty
rust:
- 1.22.1
- stable
- beta

matrix:
  include:
    - rust: nightly
      env: CARGO_FEATURE_UNSTABLE=true
  allow_failures:
    - rust: nightly

cache: cargo
