language: rust
sudo: false
dist: trusty
rust:
- 1.22.1
- stable
- beta
- nightly

matrix:
  include:
    - rust: nightly
      env: FEATURES=unstable
  allow_failures:
    - rust: nightly

cache: cargo
