[package]
name = "proptest"
version = "0.1.0"
authors = ["Jason Lingle"]
license = "MIT/Apache-2.0"
readme = "README.md"
repository = "https://github.com/altsysrq/proptest"
documentation = "https://docs.rs/proptest"
keywords = ["property", "testing", "quickcheck", "fuzz", "hypothesis"]
categories = ["development-tools::testing"]

description = """
Hypothesis-like property-based testing and shrinking.
"""

[dependencies]
rand = "0.3.15"
