[package]
name = "proptest"
version = "0.3.0"
authors = ["Jason Lingle"]
license = "MIT/Apache-2.0"
readme = "README.md"
repository = "https://github.com/altsysrq/proptest"
documentation = "https://docs.rs/proptest"
keywords = ["property", "testing", "quickcheck", "fuzz", "hypothesis"]
categories = ["development-tools::testing"]

description = """
Hypothesis-like property-based testing and shrinking.
"""

[dependencies]
bit-set = "0.4.0"
quick-error = "1.2.1"
rand = "0.3.15"
regex-syntax = "0.4.1"

[dev-dependencies]
regex = "0.2.2"
